// Database de Produtos da GlowUp Store
const PRODUCTS = [
    // SKINCARE FEMININO
    {
        id: 1,
        name: 'Sérum Facial Vitamina C',
        category: 'skincare',
        gender: 'Feminino',
        price: 89.90,
        image: 'https://www.aminhafarmacia.pt/documentos/image/produtos/catalogo/7500405.webp?v=69b96d99c6da0',
        description: 'Sérum facial com vitamina C pura para clarear e iluminar a pele.',
        fullDescription: 'Nosso Sérum Facial com Vitamina C é a solução perfeita para quem busca uma pele mais clara e iluminada. Formulado com vitamina C pura (20%), este sérum penetra profundamente na epiderme, proporcionando hidratação intensiva e proteção antioxidante.',
        specs: ['Concentração: 20% Vitamina C', 'Volume: 30ml', 'Validade: 2 anos', 'Tipo de pele: Todas'],
        benefits: ['Clareia manchas e marcas', 'Ilumina a pele naturalmente', 'Protege contra radicais livres', 'Melhora textura e tom']
    },
    {
        id: 2,
        name: 'Creme Anti-Rugas Premium',
        category: 'skincare',
        gender: 'Feminino',
        price: 124.50,
        image: 'https://wells.pt/dw/image/v2/BFLP_PRD/on/demandware.static/-/Sites-wells-master-catalog/default/dwc9a1dc93/images/wells/522/5229372-ANTI-ENVELHECIMENTO-CREME-ALTA-POTENCIA-ANTI-RUGAS-NEOSTRATA-P-06.webp?sw=774&sh=774&sm=fit&sfrm=jpg&q=90',
        description: 'Creme anti-rugas com ácido hialurônico e retinol para rejuvenescimento.',
        fullDescription: 'Creme anti-rugas desenvolvido com tecnologia avançada. Combina ácido hialurônico de diferentes pesos moleculares com retinol puro para máxima eficácia no combate aos sinais de envelhecimento.',
        specs: ['Ácido Hialurônico: Sim', 'Retinol: 0.3%', 'Textura: Creme rico', 'Volume: 50g'],
        benefits: ['Reduz rugas e linhas de expressão', 'Hidrata profundamente', 'Firma a pele', 'Resultado visível em 2 semanas']
    },
    {
        id: 3,
        name: 'Máscara Facial Hidratante',
        category: 'skincare',
        gender: 'Feminino',
        price: 45.00,
        image: 'https://ae-pic-a1.aliexpress-media.com/kf/S8549f35acfbb450fa54e5b9aa7f62a28S.jpg_960x960q75.jpg_.avif',
        description: 'Máscara facial com ingredientes naturais para hidratação profunda.',
        fullDescription: 'Máscara facial intensamente hidratante com ingredientes naturais como mel, aloe vera e camomila. Proporciona hidratação profunda em apenas 15 minutos de aplicação.',
        specs: ['Tipo: Gel/Creme', 'Volume: 100ml', 'Tempo de ação: 15 min', 'Ingredientes: Naturais'],
        benefits: ['Hidrata profundamente', 'Suaviza a pele', 'Deixa macia e maleável', 'Aromaterápico']
    },
    {
        id: 4,
        name: 'Limpador Facial Gel',
        category: 'skincare',
        gender: 'Feminino',
        price: 35.50,
        image: 'https://shopvzla.baccbeauty.com/wp-content/uploads/2024/02/SP2615-gel-limpiador-3.jpeg',
        description: 'Gel de limpeza facial com pH neutro para remover impurezas delicadamente.',
        fullDescription: 'Gel de limpeza suave com pH neutro que remove impurezas e maquiagem sem danificar o filme lipídico da pele. Ideal para uso diário e para todos os tipos de pele.',
        specs: ['Volume: 200ml', 'pH: Neutro', 'Tipo: Gel', 'Uso: Diário'],
        benefits: ['Remove impurezas', 'Não resseca', 'Deixa a pele limpa', 'Hipoalergênico']
    },
    {
        id: 5,
        name: 'Tônico Facial Clareador',
        category: 'skincare',
        gender: 'Feminino',
        price: 42.00,
        image: 'https://bemol.vtexassets.com/arquivos/ids/468093-800-800?v=638931157224230000&width=800&height=800&aspect=true',
        description: 'Tônico facial com ácido glicólico para iluminar e uniformizar o tom da pele.',
        fullDescription: 'Tônico facial com ácido glicólico que auxilia na renovação celular, deixando a pele mais clara e uniforme. Perfeito para uso após a limpeza facial.',
        specs: ['Ácido Glicólico: 5%', 'Volume: 150ml', 'Frequência: Diária', 'Tipo: Líquido'],
        benefits: ['Clareia a pele', 'Uniformiza tom', 'Renovação celular', 'Ilumina naturalmente']
    },
    {
        id: 6,
        name: 'Gel Limpador Peles Oleosas',
        category: 'skincare',
        gender: 'Masculino',
        price: 38.00,
        image: 'https://darrow.com.br/wp-content/uploads/2024/07/08-4-scaled.jpg',
        description: 'Gel limpador específico para controlar oleosidade facial.',
        fullDescription: 'Gel especialmente formulado para homens com pele oleosa. Controla a produção de sebo e deixa a pele limpa por até 8 horas.',
        specs: ['Volume: 150ml', 'Controle de oleosidade: Sim', 'Tipo: Gel', 'Uso: 2x ao dia'],
        benefits: ['Controla oleosidade', 'Matte 8 horas', 'Sem resíduos', 'Refrescante']
    },
    {
        id: 7,
        name: 'Sérum Barbear Premium',
        category: 'skincare',
        gender: 'Masculino',
        price: 62.00,
        image: 'https://via.placeholder.com/300x300?text=Sérum+Barbear',
        description: 'Sérum pré-barba que amacia os pêlos e protege a pele.',
        fullDescription: 'Sérum especial que prepara a pele para o barbear, amaciando os pêlos e criando uma camada protetora. Reduz irritações e ferimentos.',
        specs: ['Volume: 50ml', 'Amaciante: Sim', 'Protetor: Sim', 'Uso: Antes do barbear'],
        benefits: ['Amacia os pêlos', 'Reduz irritação', 'Protege a pele', 'Barbear mais suave']
    },
    {
        id: 8,
        name: 'Após Barba Cicatrizante',
        category: 'skincare',
        gender: 'Masculino',
        price: 48.50,
        image: 'https://via.placeholder.com/300x300?text=Após+Barba',
        description: 'Balm pós-barba com propriedades cicatrizantes e calmantes.',
        fullDescription: 'Bálsamo pós-barba que cicatriza pequenos ferimentos e acalma a pele irritada. Deixa a pele macia e perfumada por horas.',
        specs: ['Volume: 100ml', 'Cicatrizante: Sim', 'Aroma: Masculino', 'Hidratação: Intensa'],
        benefits: ['Cicatriza rapidamente', 'Acalma irritações', 'Hidrata a pele', 'Aroma duradouro']
    },
    {
        id: 9,
        name: 'Colágenio Hidrolisado 500g',
        category: 'suplementos',
        gender: 'Feminino',
        price: 95.00,
        image: 'https://via.placeholder.com/300x300?text=Colágenio',
        description: 'Colágenio hidrolisado em pó para saúde da pele, cabelo e unhas.',
        fullDescription: 'Colágenio hidrolisado de alta biodisponibilidade. Melhora a elasticidade da pele, fortalece cabelos e unhas. Sabor neutro, dissolve em qualquer bebida.',
        specs: ['Peso: 500g', 'Tipo: Hidrolisado', 'Origem: Bovino', 'Sabor: Neutro'],
        benefits: ['Melhora elasticidade', 'Fortalece unhas', 'Nutre cabelos', 'Articulações mais fortes']
    },
    {
        id: 10,
        name: 'Biotina Forte 60 cápsulas',
        category: 'suplementos',
        gender: 'Feminino',
        price: 72.00,
        image: 'https://via.placeholder.com/300x300?text=Biotina',
        description: 'Biotina pura para fortalecer cabelos, pele e unhas.',
        fullDescription: 'Biotina pura em alta concentração. Fortalece cabelos desde a raiz, melhora a qualidade da pele e das unhas. 1 cápsula ao dia.',
        specs: ['Quantidade: 60 cápsulas', 'Dosagem: 2.5mg', 'Origem: USA', 'Vegana: Sim'],
        benefits: ['Cabelos mais fortes', 'Unhas mais resistentes', 'Pele mais saudável', 'Resultado em 30 dias']
    },
    {
        id: 11,
        name: 'Vitamina C 1000mg 120 cápsulas',
        category: 'suplementos',
        gender: 'Feminino',
        price: 55.00,
        image: 'https://via.placeholder.com/300x300?text=Vitamina+C',
        description: 'Vitamina C pura para imunidade e beleza da pele.',
        fullDescription: 'Vitamina C em alta concentração para fortalecer a imunidade e deixar a pele mais luminosa e saudável. 1 cápsula ao dia.',
        specs: ['Dosagem: 1000mg', 'Quantidade: 120 cápsulas', 'Origem: Ácido ascórbico', 'Vegana: Sim'],
        benefits: ['Reforça imunidade', 'Ilumina a pele', 'Antioxidante poderoso', 'Energia natural']
    },
    {
        id: 12,
        name: 'Ômega 3 Premium 100 cápsulas',
        category: 'suplementos',
        gender: 'Feminino',
        price: 78.50,
        image: 'https://via.placeholder.com/300x300?text=Ômega+3',
        description: 'Ômega 3 de alta potência para saúde cardiovascular e beleza.',
        fullDescription: 'Ômega 3 concentrado com EPA e DHA. Melhora a saúde do coração, reduz inflamações e deixa a pele mais bonita e hidratada.',
        specs: ['EPA+DHA: 1000mg', 'Quantidade: 100 cápsulas', 'Origem: Peixe selvagem', 'Destilado molecularmente: Sim'],
        benefits: ['Coração saudável', 'Reduz inflamação', 'Pele hidratada', 'Sem gosto de peixe']
    },
    {
        id: 13,
        name: 'Whey Protein Isolado 2kg',
        category: 'suplementos',
        gender: 'Masculino',
        price: 145.00,
        image: 'https://via.placeholder.com/300x300?text=Whey+Protein',
        description: 'Whey protein isolado para ganho muscular e recuperação.',
        fullDescription: 'Whey protein isolado de alta pureza. Ideal para pós-treino e ganho muscular. Sabor chocolate, dissolve facilmente.',
        specs: ['Peso: 2kg', 'Tipo: Isolado', 'Proteína por dose: 30g', 'Sabor: Chocolate'],
        benefits: ['Ganho muscular', 'Recuperação rápida', 'Força aumentada', 'Resultado visível']
    },
    {
        id: 14,
        name: 'Creatina Monohidratada 300g',
        category: 'suplementos',
        gender: 'Masculino',
        price: 62.00,
        image: 'https://via.placeholder.com/300x300?text=Creatina',
        description: 'Creatina pura para ganho de força e massa muscular.',
        fullDescription: 'Creatina monohidratada 100% pura. Melhora a força, potência e ganho de massa muscular. 5g por dia.',
        specs: ['Peso: 300g', 'Tipo: Monohidratada', 'Pureza: 99.9%', 'Dose: 5g/dia'],
        benefits: ['Força aumentada', 'Massa muscular', 'Potência de treino', 'Recuperação melhorada']
    },
    {
        id: 15,
        name: 'Base Líquida Matte 30ml',
        category: 'maquiagem',
        gender: 'Feminino',
        price: 89.00,
        image: 'https://via.placeholder.com/300x300?text=Base+Líquida',
        description: 'Base líquida com efeito matte duradouro até 14 horas.',
        fullDescription: 'Base líquida de longa duração com cobertura média a alta. Efeito matte natural que dura até 14 horas sem transferência.',
        specs: ['Volume: 30ml', 'Efeito: Matte', 'Duração: 14h', 'Tons: 20 opções'],
        benefits: ['Cobertura média-alta', 'Matte por 14h', 'Sem transferência', 'Naturalmente bela']
    },
    {
        id: 16,
        name: 'Máscara de Cílios Volumizadora',
        category: 'maquiagem',
        gender: 'Feminino',
        price: 62.00,
        image: 'https://via.placeholder.com/300x300?text=Máscara+Cílios',
        description: 'Máscara volumizadora que deixa cílios 5x mais grossos.',
        fullDescription: 'Máscara de cílios com fórmula volumizadora. Deixa os cílios mais grossos e alongados em uma única aplicação.',
        specs: ['Volume: 10ml', 'Efeito: Volume 5x', 'Duração: 24h', 'Tipo: Preto intenso'],
        benefits: ['Cílios 5x mais grossos', 'Alongado e curvado', 'Preto intenso', 'À prova d\'água']
    },
    {
        id: 17,
        name: 'Paleta de Sombras 12 Cores',
        category: 'maquiagem',
        gender: 'Feminino',
        price: 98.50,
        image: 'https://via.placeholder.com/300x300?text=Paleta+Sombras',
        description: 'Paleta com 12 sombras em tons que variam de nude a smokey.',
        fullDescription: 'Paleta com 12 cores altamente pigmentadas. Fórmula cremosa que não enruga. Tons que variam de nude neutro até smokey escuro.',
        specs: ['Cores: 12', 'Pigmentação: Alta', 'Duração: 12h', 'Sem glúten'],
        benefits: ['Cores versáteis', 'Pigmentação intensa', 'Duração prolongada', 'Fácil aplicação']
    },
    {
        id: 18,
        name: 'Batom Líquido Vegano',
        category: 'maquiagem',
        gender: 'Feminino',
        price: 52.00,
        image: 'https://via.placeholder.com/300x300?text=Batom+Líquido',
        description: 'Batom líquido vegano de longa duração em 10 tons',
        fullDescription: 'Batom líquido 100% vegano com fórmula brilhante. Dura até 12 horas e não resseca os lábios. Disponível em 10 tons.',
        specs: ['Volume: 5ml', 'Efeito: Glossy', 'Duração: 12h', 'Vegano: Sim'],
        benefits: ['Cor intensa', 'Brilhante', 'Duração 12h', 'Conforto total']
    },
    {
        id: 19,
        name: 'Perfume Floral 100ml',
        category: 'perfumaria',
        gender: 'Feminino',
        price: 185.00,
        image: 'https://via.placeholder.com/300x300?text=Perfume+Floral',
        description: 'Perfume de alta concentração com notas florais e frescas.',
        fullDescription: 'Eau de Parfum com concentração de 20% de aromas. Notas florais leves com toque de frutas cítricas. Duração de até 8 horas.',
        specs: ['Volume: 100ml', 'Concentração: Eau de Parfum', 'Tipo: Floral', 'Duração: 8h'],
        benefits: ['Aroma sofisticado', 'Duração prolongada', 'Notas florais suaves', 'Elegância garantida']
    },
    {
        id: 20,
        name: 'Colônia Refrescante 150ml',
        category: 'perfumaria',
        gender: 'Feminino',
        price: 95.00,
        image: 'https://via.placeholder.com/300x300?text=Colônia',
        description: 'Colônia refrescante com notas cítricas e oceanis.',
        fullDescription: 'Colônia leve com 4% de concentração de aromas. Notas cítricas frescas com toque oceânico. Ideal para uso diário.',
        specs: ['Volume: 150ml', 'Tipo: Colônia', 'Aroma: Cítrico-Oceânico', 'Duração: 3h'],
        benefits: ['Refrescante', 'Aroma fresco', 'Uso diário', 'Embalagem elegante']
    },
    {
        id: 21,
        name: 'Perfume Amadeirado 100ml',
        category: 'perfumaria',
        gender: 'Masculino',
        price: 180.00,
        image: 'https://via.placeholder.com/300x300?text=Perfume+Amadeirado',
        description: 'Perfume com notas amadeiradas e fumadas, sofisticado.',
        fullDescription: 'Eau de Parfum com notas amadeiradas e de tabaco. Aroma sofisticado e masculino. Duração de até 10 horas.',
        specs: ['Volume: 100ml', 'Concentração: Eau de Parfum', 'Tipo: Amadeirado', 'Duração: 10h'],
        benefits: ['Aroma sofisticado', 'Duração longa', 'Notas amadeiradas', 'Charme aumentado']
    },
    {
        id: 22,
        name: 'Colônia Sport 200ml',
        category: 'perfumaria',
        gender: 'Masculino',
        price: 75.00,
        image: 'https://via.placeholder.com/300x300?text=Colônia+Sport',
        description: 'Colônia refrescante com notas de menta e citros.',
        fullDescription: 'Colônia esportiva com notas de menta, citros e almíscar. Refrescante e energizante. Ideal para uso diário.',
        specs: ['Volume: 200ml', 'Tipo: Colônia Sport', 'Aroma: Menta-Citros', 'Duração: 4h'],
        benefits: ['Refrescante', 'Energizante', 'Duração adequada', 'Versátil']
    },
    {
        id: 23,
        name: 'eBook: Guia Completo de Skincare',
        category: 'ebooks',
        gender: 'Feminino',
        price: 29.90,
        image: 'https://via.placeholder.com/300x300?text=eBook+Skincare',
        description: 'Guia completo com rotinas de skincare para cada tipo de pele.',
        fullDescription: 'eBook com mais de 100 páginas sobre skincare. Inclui rotinas personalizadas, ingredientes explicados e dicas de especialistas.',
        specs: ['Formato: PDF', 'Páginas: 120', 'Acesso: Vitalício', 'Idioma: Português'],
        benefits: ['Conhecimento completo', 'Acesso permanente', 'Dicas de especialistas', 'Guia prático']
    },
    {
        id: 24,
        name: 'eBook: Nutrição para Beleza',
        category: 'ebooks',
        gender: 'Unissex',
        price: 34.90,
        image: 'https://via.placeholder.com/300x300?text=eBook+Nutrição',
        description: 'Guia de nutrição para potencializar a beleza de dentro para fora.',
        fullDescription: 'eBook sobre nutrição aplicada à beleza. Alimentos que melhoram pele, cabelo e unhas. Receitas exclusivas incluídas.',
        specs: ['Formato: PDF', 'Páginas: 150', 'Receitas: 30', 'Acesso: Vitalício'],
        benefits: ['Nutrição eficaz', 'Receitas práticas', 'Beleza natural', 'Ciência comprovada']
    },
    {
        id: 25,
        name: 'eBook: Rotina de Beleza para Homens',
        category: 'ebooks',
        gender: 'Masculino',
        price: 27.90,
        image: 'https://via.placeholder.com/300x300?text=eBook+Homens',
        description: 'Guia prático sobre rotina de beleza e cuidados para homens.',
        fullDescription: 'eBook específico para homens com rotina simples e eficaz. Desde limpeza até estratégias anti-barba. Passo a passo prático.',
        specs: ['Formato: PDF', 'Páginas: 80', 'Dicas: 50+', 'Acesso: Vitalício'],
        benefits: ['Prático e objetivo', 'Simples de seguir', 'Resultados comprovados', 'Pra homens mesmo']
    },
    {
        id: 26,
        name: 'Receita: Smoothie Colágeno Natural',
        category: 'receitas',
        gender: 'Feminino',
        price: 12.90,
        image: 'https://via.placeholder.com/300x300?text=Receita+Smoothie',
        description: 'Receita de smoothie que estimula produção de colágeno natural.',
        fullDescription: 'Receita simples de smoothie com frutas vermelhas, iogurte e frutas que estimulam colágeno. Modo de preparo passo a passo com ingredientes acessíveis.',
        specs: ['Tipo: Digital', 'Modo: Preparação', 'Tempo: 10 min', 'Valor: Único'],
        benefits: ['Simples de fazer', 'Ingredientes acessíveis', 'Colágeno natural', 'Muito saudável']
    },
    {
        id: 27,
        name: 'Receita: Máscara Facial Caseira',
        category: 'receitas',
        gender: 'Feminino',
        price: 9.90,
        image: 'https://via.placeholder.com/300x300?text=Receita+Máscara',
        description: 'Receita de máscara facial hidratante feita em casa.',
        fullDescription: 'Receita simples de máscara facial com ingredientes naturais. Ingredientes: mel, abacate, óleo de coco. Modo de preparo detalhado.',
        specs: ['Tipo: Digital', 'Ingredientes: Naturais', 'Modo: Preparação', 'Eficácia: Alta'],
        benefits: ['100% natural', 'Muito barato', 'Eficaz demais', 'Acesso permanente']
    },
    {
        id: 28,
        name: 'Receita: Chá de Colágeno',
        category: 'receitas',
        gender: 'Unissex',
        price: 14.90,
        image: 'https://via.placeholder.com/300x300?text=Receita+Chá',
        description: 'Receita de chá natural que estimula colágeno e hidratação.',
        fullDescription: 'Receita de chá com ingredientes naturais que estimulam a produção de colágeno. Inclui variações com diferentes ervas e frutas.',
        specs: ['Tipo: Digital', 'Variações: 5', 'Tempo: 15 min', 'Ingredientes: Naturais'],
        benefits: ['Saudável', 'Gostoso', 'Colágeno natural', 'Acesso vitalício']
    },
    {
        id: 29,
        name: 'Receita: Suco Desintoxicante',
        category: 'receitas',
        gender: 'Unissex',
        price: 11.90,
        image: 'https://via.placeholder.com/300x300?text=Receita+Suco',
        description: 'Receita de suco natural que desintoxica e ilumina a pele.',
        fullDescription: 'Receita de suco com maçã, cenoura, gengibre e limão. Detoxifica o organismo e deixa a pele naturalmente iluminada.',
        specs: ['Tipo: Digital', 'Ingredientes: Naturais', 'Tempo: 10 min', 'Benefícios: Múltiplos'],
        benefits: ['Desintoxica', 'Ilumina pele', 'Muito saudável', 'Refrescante']
    },
    {
        id: 30,
        name: 'Receita: Açaí Bowl Antioxidante',
        category: 'receitas',
        gender: 'Unissex',
        price: 13.90,
        image: 'https://via.placeholder.com/300x300?text=Receita+Açaí',
        description: 'Receita de açaí bowl com toppings que potencializam antioxidantes.',
        fullDescription: 'Receita completa de açaí bowl com frutas vermelhas, sementes e toppings que potencializam a ação antioxidante. Perfeito para café da manhã.',
        specs: ['Tipo: Digital', 'Toppings: 8 opções', 'Tempo: 5 min', 'Valor: Nutritivo alto'],
        benefits: ['Antioxidante', 'Delicioso', 'Fácil de fazer', 'Muito nutritivo']
    }
];
