// ✅ SEGURO - Apenas IDs e informações públicas básicas
// ✅ Preços NÃO são incluídos aqui (virão do servidor)

const PRODUCTS = [
    // SKINCARE FEMININO
    { id: 1, name: 'Sérum Facial Vitamina C', category: 'skincare', gender: 'Feminino', image: 'https://via.placeholder.com/300x300?text=Sérum+Vitamina+C', description: 'Sérum facial com vitamina C pura para clarear e iluminar a pele.', fullDescription: 'Nosso Sérum Facial com Vitamina C é a solução perfeita para quem busca uma pele mais clara e iluminada. Formulado com vitamina C pura (20%), este sérum penetra profundamente na epiderme, proporcionando hidratação intensiva e proteção antioxidante.', specs: ['Concentração: 20% Vitamina C', 'Volume: 30ml', 'Validade: 2 anos', 'Tipo de pele: Todas'], benefits: ['Clareia manchas e marcas', 'Ilumina a pele naturalmente', 'Protege contra radicais livres', 'Melhora textura e tom'] },
    { id: 2, name: 'Creme Anti-Rugas Premium', category: 'skincare', gender: 'Feminino', image: 'https://via.placeholder.com/300x300?text=Creme+Anti-Rugas', description: 'Creme anti-rugas com ácido hialurônico e retinol para rejuvenescimento.', fullDescription: 'Creme anti-rugas desenvolvido com tecnologia avançada. Combina ácido hialurônico de diferentes pesos moleculares com retinol puro para máxima eficácia no combate aos sinais de envelhecimento.', specs: ['Ácido Hialurônico: Sim', 'Retinol: 0.3%', 'Textura: Creme rico', 'Volume: 50g'], benefits: ['Reduz rugas e linhas de expressão', 'Hidrata profundamente', 'Firma a pele', 'Resultado visível em 2 semanas'] },
    { id: 3, name: 'Máscara Facial Hidratante', category: 'skincare', gender: 'Feminino', image: 'https://via.placeholder.com/300x300?text=Máscara+Hidratante', description: 'Máscara facial com ingredientes naturais para hidratação profunda.', fullDescription: 'Máscara facial intensamente hidratante com ingredientes naturais como mel, aloe vera e camomila. Proporciona hidratação profunda em apenas 15 minutos de aplicação.', specs: ['Tipo: Gel/Creme', 'Volume: 100ml', 'Tempo de ação: 15 min', 'Ingredientes: Naturais'], benefits: ['Hidrata profundamente', 'Suaviza a pele', 'Deixa macia e maleável', 'Aromaterápico'] },
    { id: 4, name: 'Limpador Facial Gel', category: 'skincare', gender: 'Feminino', image: 'https://via.placeholder.com/300x300?text=Limpador+Facial', description: 'Gel de limpeza facial com pH neutro para remover impurezas delicadamente.', fullDescription: 'Gel de limpeza suave com pH neutro que remove impurezas e maquiagem sem danificar o filme lipídico da pele. Ideal para uso diário e para todos os tipos de pele.', specs: ['Volume: 200ml', 'pH: Neutro', 'Tipo: Gel', 'Uso: Diário'], benefits: ['Remove impurezas', 'Não resseca', 'Deixa a pele limpa', 'Hipoalergênico'] },
    { id: 5, name: 'Tonalizante Facial Tônico', category: 'skincare', gender: 'Feminino', image: 'https://via.placeholder.com/300x300?text=Tonalizante+Facial', description: 'Tonalizante facial suave para equilibrar e revigorar a pele.', fullDescription: 'Tonalizante facial desenvolvido para equilibrar o pH da pele após a limpeza. Contém ingredientes suavizantes que preparam a pele para os tratamentos posteriores, deixando-a macia e revigorada.', specs: ['Volume: 150ml', 'pH: Balanceado', 'Tipo: Líquido', 'Aplicação: Tônico'], benefits: ['Equilibra pH', 'Prepara para serum', 'Refrescante', 'Absorção rápida'] },
    { id: 6, name: 'Tratamento Noturno Regenerador', category: 'skincare', gender: 'Feminino', image: 'https://via.placeholder.com/300x300?text=Tratamento+Noturno', description: 'Creme noturno regenerador para renovação da pele enquanto dorme.', fullDescription: 'Creme noturno especialmente formulado para aproveitar o período de regeneração natural da pele durante o sono. Promove renovação celular, deixando a pele revitalizada e radiante pela manhã.', specs: ['Volume: 50g', 'Textura: Creme rico', 'Aplicação: Noturna', 'Tipo: Regenerador'], benefits: ['Regenera células', 'Noite reparadora', 'Pele renovada', 'Aroma relaxante'] },

    // MAQUIAGEM FEMININO
    { id: 7, name: 'Base Líquida Cobertura Total', category: 'maquiagem', gender: 'Feminino', image: 'https://via.placeholder.com/300x300?text=Base+Líquida', description: 'Base líquida com cobertura total e acabamento mate duradouro.', fullDescription: 'Base líquida profissional com fórmula resistente à água e suor. Oferece cobertura total que disfarça imperfeições e proporciona acabamento mate e uniforme por até 16 horas.', specs: ['Volume: 30ml', 'Acabamento: Mate', 'Durabilidade: 16h', 'Impermeável: Sim'], benefits: ['Cobertura total', 'Acabamento mate', 'Longa duração', 'Resistente à água'] },
    { id: 8, name: 'Pó Compacto Fixador', category: 'maquiagem', gender: 'Feminino', image: 'https://via.placeholder.com/300x300?text=Pó+Compacto', description: 'Pó compacto para fixar maquiagem e acabamento perfeito.', fullDescription: 'Pó compacto ultra-fino que fixa a maquiagem, controla o brilho e oferece um acabamento perfeito. Ideal para retoques durante o dia.', specs: ['Peso: 10g', 'Tipo: Compacto', 'Acabamento: Matte', 'Reusável: Sim'], benefits: ['Fixa maquiagem', 'Controla brilho', 'Acabamento perfeito', 'Leve'] },
    { id: 9, name: 'Paleta de Sombras 12 Cores', category: 'maquiagem', gender: 'Feminino', image: 'https://via.placeholder.com/300x300?text=Paleta+Sombras', description: 'Paleta de sombras com 12 cores pigmentadas e de longa duração.', fullDescription: 'Paleta profissional com 12 cores altamente pigmentadas, combinando tons neutros, quentes e frios. Perfeita para criar looks variados, desde naturais até dramáticos.', specs: ['Quantidade: 12 cores', 'Pigmentação: Alta', 'Durabilidade: 12h', 'Texturas: Matte e Shimmer'], benefits: ['Cores ricas', 'Versátil', 'Longa duração', 'Profissional'] },
    { id: 10, name: 'Delineador Líquido Preto', category: 'maquiagem', gender: 'Feminino', image: 'https://via.placeholder.com/300x300?text=Delineador+Líquido', description: 'Delineador líquido com ponta de precisão para traços perfeitos.', fullDescription: 'Delineador líquido com fórmula à prova d\'água e ponta ultrafina que permite traços precisos e perfeitos. Pigmentação intensa que não desbota durante o dia.', specs: ['Volume: 5ml', 'Ponta: Ultrafina', 'Cor: Preto intenso', 'Durabilidade: 24h'], benefits: ['Traços precisos', 'Prova d\'água', 'Longa duração', 'Cor intensa'] },
    { id: 11, name: 'Batom Veludo Matte', category: 'maquiagem', gender: 'Feminino', image: 'https://via.placeholder.com/300x300?text=Batom+Veludo', description: 'Batom com textura veludo e acabamento matte irresistível.', fullDescription: 'Batom com textura matte aveludada que dura até 8 horas sem deixar resíduos. Disponível em várias cores clássicas que combinam com qualquer look.', specs: ['Peso: 3.5g', 'Acabamento: Matte', 'Durabilidade: 8h', 'Cores: Variadas'], benefits: ['Textura matte', 'Longa duração', 'Cores variadas', 'Confortável'] },
    { id: 12, name: 'Rímel Volumizador Extra', category: 'maquiagem', gender: 'Feminino', image: 'https://via.placeholder.com/300x300?text=Rímel+Volumizador', description: 'Rímel volumizador com escova espiral para cílios impecáveis.', fullDescription: 'Rímel com escova especial em espiral que captura cada cilhinho, proporcionando volume e alongamento extremos. Fórmula resistente à água garante cílios lindos o dia todo.', specs: ['Volume: 8ml', 'Efeito: Volumizador', 'Impermeável: Sim', 'Durabilidade: 24h'], benefits: ['Volume extremo', 'Alongamento', 'Prova d\'água', 'Cílios perfeitos'] },

    // PERFUMARIA
    { id: 13, name: 'Perfume Floral Feminino', category: 'perfumaria', gender: 'Feminino', image: 'https://via.placeholder.com/300x300?text=Perfume+Floral', description: 'Perfume com notas florais suaves e elegantes.', fullDescription: 'Perfume premium com notas florais sofisticadas. Combina fragrâncias de rosa, jasmim e gardênia, criando um aroma delicado e envolvente que marca presença sutilmente.', specs: ['Volume: 100ml', 'Concentração: 3%', 'Durabilidade: 6h', 'Notas: Florais'], benefits: ['Aroma delicado', 'Elegante', 'Longa duração', 'Sofisticado'] },
    { id: 14, name: 'Perfume Frutado Feminino', category: 'perfumaria', gender: 'Feminino', image: 'https://via.placeholder.com/300x300?text=Perfume+Frutado', description: 'Perfume com notas frutadas refrescantes e energéticas.', fullDescription: 'Perfume refrescante com notas de framboesa, melancia e morango. Transmite energia e vitalidade, perfeito para o dia a dia ou ocasiões especiais.', specs: ['Volume: 100ml', 'Concentração: 3%', 'Durabilidade: 6h', 'Notas: Frutadas'], benefits: ['Refrescante', 'Energético', 'Vibrante', 'Delicioso'] },
    { id: 15, name: 'Colônia Corporal Feminina', category: 'perfumaria', gender: 'Feminino', image: 'https://via.placeholder.com/300x300?text=Colônia+Corporal', description: 'Colônia corporal leve e revigorante para o corpo inteiro.', fullDescription: 'Colônia corporal refrescante com baixa concentração de essências. Ideal para aplicar no corpo inteiro, oferecendo um aroma fresco e duradouro sem ser tão intenso quanto um perfume.', specs: ['Volume: 150ml', 'Concentração: 1%', 'Durabilidade: 4h', 'Tipo: Colônia'], benefits: ['Leve', 'Fresco', 'Revigorante', 'Corporal'] },

    // SUPLEMENTOS MASCULINO
    { id: 16, name: 'Whey Protein Chocolate', category: 'suplementos', gender: 'Masculino', price: 89.90, image: 'https://via.placeholder.com/300x300?text=Whey+Protein', description: 'Whey protein concentrado com sabor chocolate para ganho muscular.', fullDescription: 'Whey protein de alta qualidade com 20g de proteína por dose. Formulado para recuperação muscular e ganho de massa magra. Absorção rápida e delicioso sabor chocolate.', specs: ['Peso: 1kg', 'Proteína: 20g/dose', 'Sabor: Chocolate', 'Tipo: Concentrado'], benefits: ['Ganho muscular', 'Recuperação', 'Proteína pura', 'Delicioso'] },
    { id: 17, name: 'BCAA 2:1:1', category: 'suplementos', gender: 'Masculino', image: 'https://via.placeholder.com/300x300?text=BCAA', description: 'BCAA na proporção 2:1:1 para treinos intensos.', fullDescription: 'Aminoácidos essenciais em proporção 2:1:1 (Leucina, Isoleucina e Valina) para potencializar seus treinos. Reduz fadiga muscular e promove recuperação rápida.', specs: ['Peso: 300g', 'Porções: 60', 'Sabor: Tropical', 'Proporção: 2:1:1'], benefits: ['Reduz fadiga', 'Recuperação', 'Desempenho', 'Energia'] },
    { id: 18, name: 'Creatina Monohidratada', category: 'suplementos', gender: 'Masculino', image: 'https://via.placeholder.com/300x300?text=Creatina', description: 'Creatina monohidratada pura para força e poder.', fullDescription: 'Creatina monohidratada de grau farmaêutico. Aumenta força, potência e resistência muscular. Garantida 99,9% de pureza.', specs: ['Peso: 300g', 'Pureza: 99.9%', 'Tipo: Monohidratada', 'Porções: 100'], benefits: ['Aumenta força', 'Potência', 'Resistência', 'Pura'] },
    { id: 19, name: 'Pré-Treino Explosão', category: 'suplementos', gender: 'Masculino', image: 'https://via.placeholder.com/300x300?text=Pré-Treino', description: 'Pré-treino com cafeína e estimulantes para máxima energia.', fullDescription: 'Fórmula pré-treino com cafeína, beta-alanina e arginina. Proporciona explosão de energia, melhor foco e pump muscular intenso.', specs: ['Peso: 300g', 'Cafeína: 200mg/dose', 'Sabor: Melancia', 'Tipo: Pré-treino'], benefits: ['Energia explosiva', 'Foco total', 'Pump intenso', 'Máximo desempenho'] },
    { id: 20, name: 'Multivitamínico Premium', category: 'suplementos', gender: 'Masculino', image: 'https://via.placeholder.com/300x300?text=Multivitamínico', description: 'Multivitamínico com 30+ nutrientes essenciais.', fullDescription: 'Fórmula completa com 30+ vitaminas e minerais essenciais. Suporta saúde geral, imunidade e bem-estar. Ideal para quem treina intensamente.', specs: ['Quantidade: 100 cápsulas', 'Nutrientes: 30+', 'Dose: 1 cápsula', 'Vegan: Sim'], benefits: ['Saúde completa', 'Imunidade', 'Bem-estar', 'Energia'] },

    // CUIDADOS MASCULINO
    { id: 21, name: 'Shampoo Barba Forte', category: 'skincare', gender: 'Masculino', image: 'https://via.placeholder.com/300x300?text=Shampoo+Barba', description: 'Shampoo especializado para limpeza profunda da barba.', fullDescription: 'Shampoo especialmente formulado para barbas. Remove resíduos mantendo a hidratação natural dos pelos. Com ingredientes naturais que fortalecem e embelezam a barba.', specs: ['Volume: 250ml', 'Tipo: Específico para barba', 'Ingredientes: Naturais', 'Aroma: Amadeirado'], benefits: ['Limpeza profunda', 'Fortalece', 'Hidrata', 'Aroma'] },
    { id: 22, name: 'Óleo Barba Premium', category: 'skincare', gender: 'Masculino', image: 'https://via.placeholder.com/300x300?text=Óleo+Barba', description: 'Óleo para barba com aromas sofisticados e nutrientes.', fullDescription: 'Óleo premium para barba com ingredients naturais que hidratam, amaciam e deixam a barba mais brilhante e saudável. Aroma sofisticado e duradouro.', specs: ['Volume: 50ml', 'Ingredientes: Naturais', 'Aroma: Amadeirado', 'Tipo: Óleo'], benefits: ['Hidrata barba', 'Amaciante', 'Brilho natural', 'Aroma duradouro'] },
    { id: 23, name: 'Balm Modelador Barba', category: 'skincare', gender: 'Masculino', image: 'https://via.placeholder.com/300x300?text=Balm+Barba', description: 'Balm para modelar e manter a forma da barba.', fullDescription: 'Balm firme mas confortável para modelar a barba mantendo a forma o dia todo. Oferece controle sem deixar a barba rígida ou com aparência pegajosa.', specs: ['Peso: 60g', 'Fixação: Forte', 'Acabamento: Natural', 'Tipo: Balm'], benefits: ['Modela', 'Mantém forma', 'Controle forte', 'Natural'] },
    { id: 24, name: 'Desodorizante Masculino', category: 'skincare', gender: 'Masculino', image: 'https://via.placeholder.com/300x300?text=Desodorante', description: 'Desodorizante com proteção 48h e aroma fresco.', fullDescription: 'Desodorizante de alta performance com proteção por 48 horas. Controla suor e odor mesmo em dias intensos de atividades. Aroma fresco e duradouro.', specs: ['Volume: 150ml', 'Proteção: 48h', 'Tipo: Spray', 'Aroma: Fresco'], benefits: ['Proteção 48h', 'Controla suor', 'Aroma fresco', 'Performance'] },
    { id: 25, name: 'Hidratante Facial Homem', category: 'skincare', gender: 'Masculino', image: 'https://via.placeholder.com/300x300?text=Hidratante+Homem', description: 'Hidratante facial leve para a pele masculina.', fullDescription: 'Hidratante especialmente desenvolvido para a pele masculina. Fórmula leve que hidrata sem deixar aparência oleosa ou pegajosa. Absorção rápida.', specs: ['Volume: 100ml', 'Tipo: Hidratante', 'Para: Homem', 'Acabamento: Matte'], benefits: ['Hidrata', 'Leve', 'Matte', 'Rápido'] },
    { id: 26, name: 'Protetor Solar Facial 50+', category: 'skincare', gender: 'Masculino', image: 'https://via.placeholder.com/300x300?text=Protetor+Solar', description: 'Protetor solar FPS 50+ resistente à água.', fullDescription: 'Protetor solar de amplo espectro com FPS 50+ que protege contra raios UVA e UVB. Resistente à água por até 80 minutos, ideal para atividades ao ar livre.', specs: ['Volume: 100ml', 'FPS: 50+', 'Resistência: 80min', 'Tipo: Facial'], benefits: ['Proteção máxima', 'Resiste água', 'Amplo espectro', 'Essencial'] },

    // EBOOKS E CONHECIMENTO
    { id: 27, name: 'eBook Guia Skincare', category: 'eBooks', gender: 'Feminino', image: 'https://via.placeholder.com/300x300?text=eBook+Skincare', description: 'Guia completo de skincare adaptado para cada tipo de pele.', fullDescription: 'Guia digital abrangente sobre rotina de skincare, como escolher produtos certos e dicas profissionais de dermatologistas. PDF completo com 100+ páginas.', specs: ['Formato: PDF', 'Páginas: 100+', 'Atualizado: 2026', 'Acesso: Vitalício'], benefits: ['Conhecimento profissional', 'Rotinas personalizadas', 'Dicas expert', 'Sempre acessível'] },
    { id: 28, name: 'eBook Maquiagem Básica', category: 'eBooks', gender: 'Feminino', image: 'https://via.placeholder.com/300x300?text=eBook+Maquiagem', description: 'Tutorial de maquiagem básica e avançada com passo a passo.', fullDescription: 'eBook completo com técnicas de maquiagem desde o básico até o avançado. Inclui 50+ tutoriais em video (links) e guia de compras de produtos essenciais.', specs: ['Formato: PDF + Vídeos', 'Páginas: 80+', 'Tutoriais: 50+', 'Acesso: Vitalício'], benefits: ['Técnicas profissionais', 'Passo a passo', 'Vídeos inclusos', 'Sempre atualizado'] },
    { id: 29, name: 'eBook Nutrição para Atletas', category: 'eBooks', gender: 'Masculino', image: 'https://via.placeholder.com/300x300?text=eBook+Nutrição', description: 'Guia completo de nutrição e suplementação para atletas.', fullDescription: 'eBook escrito por nutricionista especializado. Aborda nutrição ideal, suplementação correta, planos de refeição e muito mais. 120+ páginas de conhecimento puro.', specs: ['Formato: PDF', 'Páginas: 120+', 'Autor: Nutricionista', 'Acesso: Vitalício'], benefits: ['Expert guidance', 'Planos personalizados', 'Ciência comprovada', 'Resultado garantido'] },
    { id: 30, name: 'eBook Treino em Casa', category: 'eBooks', gender: 'Masculino', image: 'https://via.placeholder.com/300x300?text=eBook+Treino', description: 'Programas de treino sem equipamento para fazer em casa.', fullDescription: 'eBook com 5 programas completos de treino, do iniciante ao avançado. Sem equipamento necessário, apenas seu peso corporal. Inclui vídeos de forma correta.', specs: ['Formato: PDF + Vídeos', 'Programas: 5', 'Duração: 8-12 semanas', 'Acesso: Vitalício'], benefits: ['Sem equipamento', 'Em qualquer lugar', 'Progressivo', 'Resultados reais'] },

    // RECEITAS
    { id: 31, name: 'Livro Receitas Saudáveis', category: 'receitas', gender: 'Feminino', image: 'https://via.placeholder.com/300x300?text=Livro+Receitas', description: 'Livro com 100+ receitas saudáveis e deliciosas.', fullDescription: 'Livro com receitas saudáveis desenvolvidas por nutricionista. Desde café da manhã até sobremesas light. Cada receita tem calorias e macros calculadas.', specs: ['Formato: PDF', 'Receitas: 100+', 'Com macros: Sim', 'Acesso: Vitalício'], benefits: ['Saudável', 'Delicioso', 'Nutricionista', 'Macros inclusos'] },
    { id: 32, name: 'Plano Refeições 30 Dias', category: 'receitas', gender: 'Masculino', image: 'https://via.placeholder.com/300x300?text=Plano+Refeições', description: 'Plano completo de refeições para 30 dias com ganho muscular.', fullDescription: 'Plano de refeições de 30 dias com todas as refeições calculadas em macros para ganho muscular. Inclui lista de compras completa e modo de preparo.', specs: ['Formato: PDF', 'Dias: 30', 'Foco: Ganho muscular', 'Com receitas: Sim'], benefits: ['Fácil seguir', 'Macros perfeitos', 'Ganha músculo', 'Sem adivinhações'] }
];

// ✅ FUNÇÃO PARA OBTER PREÇO DO SERVIDOR (simula chamada à API)
// Em produção, isso viria de um servidor seguro
function getPriceFromServer(productId, quantity = 1) {
    // ⚠️ ISSO DEVERIA VIR DE UM SERVIDOR REAL
    // Mantém preços aqui apenas para demonstração local
    
    const PRICES = {
        1: 89.90, 2: 124.50, 3: 45.00, 4: 35.50, 5: 52.00, 6: 98.90,
        7: 67.50, 8: 45.00, 9: 89.90, 10: 52.00, 11: 45.00, 12: 62.00,
        13: 89.90, 14: 89.90, 15: 45.00, 16: 89.90, 17: 89.90, 18: 45.00,
        19: 62.00, 20: 52.00, 21: 45.00, 22: 67.50, 23: 45.00, 24: 35.50,
        25: 52.00, 26: 62.00, 27: 29.90, 28: 39.90, 29: 49.90, 30: 39.90,
        31: 59.90, 32: 79.90
    };
    
    return PRICES[productId] || 0;
}

// ✅ FUNÇÃO PARA OBTER PRODUTO COM PREÇO VALIDADO
function getProductWithPrice(productId) {
    const product = PRODUCTS.find(p => p.id === productId);
    if (!product) return null;
    
    return {
        ...product,
        price: getPriceFromServer(productId) // Preço do servidor
    };
}

console.log('✅ products-secure.js carregado - Apenas IDs e informações públicas');
